
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Build DApp
        run: pnpm --dir apps/dapp build
      - name: Build Site
        run: pnpm --dir apps/site build
      - name: Compile EVM Contracts
        run: pnpm --dir contracts-evm build
      - name: Test EVM Contracts
        run: pnpm --dir contracts-evm test
